### PR TITLE
It is a40 not a40dd

### PR DESCRIPTION
**Pull request by crazo7924**
Also adds backup of DTB and DTBO partitions.

If any queries, please do comment

### CODE REVIEW

**Comment by ponces** [comment]
First of all, thank you for the pull request.
The device name was "a40dd" instead of "a40" because it was based on geiti94's work. Nevertheless, i will accept your change.
Also, I successfully compiled with your changes but you also need to rename the "omni_a40dd.mk" makefile to "omni_a40.mk" due to the device rename.
Could you please commit this name change without closing this pull request or creating a new one?

**Comment by crazo7924** [comment]
@ponces Ha I forgot about that. Also, the repository name would need a change.

**Comment by crazo7924** [comment]
It's done

**Comment by crazo7924** [comment]
Do notice omni_a40.mk(#L18,) the product name is still a40dd

**Comment by ponces** [comment]
Based on the device's getprops, it is either a40xx (ro.product.vendor.name) or a40 (ro.product.name).
So, if it's not too much of an effort, please also update PRODUCT_RELEASE_NAME on the file you mentioned.

**Comment by crazo7924** [comment]
@ponces please compare build fingerprint of oneui and twrp with my changes

**Comment by ponces** [comment]
Did you check my reply above?
a40xx - ro.product.vendor.name
a40 - ro.product.name
So I believe PRODUCT_RELEASE_NAME should be also updated from a40dd to a40.
Do you agree?

**Comment by crazo7924** [comment]
There are two different props for a reason - a40 means Galaxy A40 and the other one a40dd means a specific variety of A40.

For TWRP I think the release name should be a40xx as it is universal.
Anyway, it doesn't affect the working of TWRP, only the build-fingerprint changes

**Comment by ponces** [comment]
It is confusing, I know, but I believe you are also mixing things up.

The current TWRP's fingerprint (without this PR) is something like
`Samsung/omni_a40dd/a40dd:9/PQ3B.190801.002/ponces12070032:eng/test-keys`

With your changes, this would become:
`samsung/omni_a40/a40dd:9/PQ3B.190801.002/ponces12070032:eng/test-keys`

And with the further change that I am proposing, it would become:
`samsung/omni_a40/a40:9/PQ3B.190801.002/ponces12070032:eng/test-keys`

Which is even more accurate. Right?
For the fingerprints, original and TWRP, to be more similar, "omni_a40" would not even be a proper product name.

**Pull request merged**
